version: '2.4'

services:
  redis:
    image: redis:5.0.5-alpine3.10
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 6379

  proxy:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: redis:6379
      HTTP_LISTEN_PORT: 8383
      TCP_LISTEN_PORT: ":6379"
      CACHE_TTL: 60
      CACHE_CAPACITY: 100
    ports:
      - 8383:8383
      - 6379

  test:
    build:
      context: .
      target: builder
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: redis:6379
      CACHE_TTL: 60
      CACHE_CAPACITY: 10
      DOCKER: "true"
    command: ["go", "test", "-v", "./..."]
